---------------
1. What is a Python library? Why do we use Python libraries?

Python library is a collection of modules and functions that can be used by other programs.
These libraries are imported and installed into the Python environment to make the program easier to use.
The capabilities of these libraries are:

1. Data Analysis and Visualization: It helps in the analysis of data and visualization of data. Libraries include pandas, matplotlib.

2. Machine Learning: It helps in the machine learning and deep learning. Libraries include scikit-learn, tensorflow, keras

3. Web development: It helps in the web development and web scrapping. Libraries include requests, bs4, selenium for web scrapping and flask, django for web development.

4. Networking and Communication: Libraries like requests, socket, urllib are responsible for http requests, networking and communication with various web services.

5. GUI development: Libraries like Tkinter, PyQT, Qt are used for GUI development.

6. Natural Language Processing: Libraries like spacy, nltk are used for Natural Language Processing.

7. File I/O: Libraries like os, csv, shutil are used for file I/O.

8. Testing: Libraries like unittest, pytest are used for testing.

Uses of python libraries

1. Improved code reusability: It makes the code more readable and maintainable.

2. Save time: It saves time in development and debugging.

3. Standarization and consistency: It helps in standardization of data and consistent data representation.

4. Innovation and efficiency: It improves the efficiency of the program and provides better functionalities.



-----------
2. What is the difference between Numpy array and List?

In [10]:
data = [
     ["Numpy array can  store mixed type of data.", "List can store only one type of data."],
     ["Numpy array is faster than list.", "List is slower than Numpy array."],
     ["Numpy array is easier to work with.", "List is easier to work with."],
     ["Numerical data stored in memory is more efficient.", "Numerical data stored in memory is less efficient."],
     ["Slicing and indexing is advanced.", "Slicing and indexing is basic."],
     ["One-dimensional array", "Can be made multidimensional."]
]

print("| NumPy Array | List |")
print("|---|---|")

for row in data:
    print("| " + row[0] + " | " + row[1] + " |")


| NumPy Array | List |
|---|---|
| Numpy array can  store mixed type of data. | List can store only one type of data. |
| Numpy array is faster than list. | List is slower than Numpy array. |
| Numpy array is easier to work with. | List is easier to work with. |
| Numerical data stored in memory is more efficient. | Numerical data stored in memory is less efficient. |
| Slicing and indexing is advanced. | Slicing and indexing is basic. |
| One-dimensional array | Can be made multidimensional. |


----------
3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print("array shape:",arr.shape)
print("array size:",arr.size)
print("array dimension:",arr.ndim)

array shape: (3, 4)
array size: 12
array dimension: 2


--------
4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
first_row = arr[0]
print(first_row)

[1 2 3 4]


-------------
5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [13]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
second_third = arr[2, 3]
print("element at second row and third column:", second_third)

element at second row and third column: 12


-------
6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
odd_elements = arr[:, 1::2]
print("odd elements:", odd_elements)


odd elements: [[ 2  4]
 [ 6  8]
 [10 12]]


---
7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [15]:
arr = np.random.rand(3, 3)
print(arr)

[[0.53769249 0.90552935 0.20478855]
 [0.26085011 0.92258779 0.9085714 ]
 [0.65888892 0.43900676 0.57838722]]


-------
8. Describe the difference between np.random.rand and np.random.randn?

* np.random.rand(d0, d1, ..., dn):

1. Generates samples from a uniform distribution on the interval [0, 1). The interval includes 0, but not 1. 

2. This distribution is also referred to as the standard uniform distribution. 

3. Its commonly used for generating random numbers for simulations or statistical modeling.

* np.random.randn(d0, d1, ..., dn):

1. Generates samples from a standard normal distribution (also known as the Gaussian distribution) with a mean of 0 and a standard deviation of 1.

2. This distribution has a bell-shaped curve with most values concentrated around the mean (0) and fewer values farther out in the tails.

3. It's commonly used for generating random noise with a normal distribution for simulations or statistical modeling.

---
9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [16]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
new_arr = np.expand_dims(arr, axis=1)
print(new_arr.shape)

(3, 1, 4)


---
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [17]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
transposed_arr = arr.T
print(transposed_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


-----
11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matics
4. Subtract matrix B from A 
5. Divide Matrix B by A

In [18]:
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])


element_wise = A2 * B2
print("Element-wise multiplication:", element_wise)

A = A2.T 
matrix_product = np.matmul(A, B2)
print("Matrix multiplication:", matrix_product)


matrix_sum = A2 + B2
print("Matrix sum:", matrix_sum)


matrix_difference = A2 - B2
print("Matrix difference (A - B):", matrix_difference)


matrix_division = np.true_divide(B2, A2)
print("Matrix division (B / A, element-wise):", matrix_division)

Element-wise multiplication: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication: [[107 122 137 152]
 [122 140 158 176]
 [137 158 179 200]
 [152 176 200 224]]
Matrix sum: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix difference (A - B): [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matrix division (B / A, element-wise): [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


-------------
12. Which function in Numpy can be used to swap the byte order of an array?

The function in numpy is np.ndarray.byteswap(). Its method applied to an array to toogle the byte order of the array.

------
13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in numpy is used to calculate the inverse of a matrix.

A * A⁻¹ = I



---------
14. What does the np.reshape function do, and how is it used?

The np.reshape is used to change the shape of an array without changing its data. It allows rearranging the elements of an array in a particular way.

Use cases:

1. Changing the number of rows and columns of an array to make it more compact or easier to work with.
2. It is also used to remove dimensions of the array that are not needed.
3. Flattens the array into a 1D array.

-----
15. What is broadcasting in Numpy?

Broadcasting in NumPy is used to perform operations on arrays of different shapes. It automatically expands the smaller array to match the shape of the larger array.
